
export const imageSource = {
    logo: require('../assets/images/logo.png'),
   icon_order: require('../assets/images/orderempty.png'),
    // headlogo: require('../assets/images/headlogo.png'),
    // headlogo2: require('../assets/images/headlogo2.png'),
    // headlogo3: require('../assets/images/headlogo3.png'),
    //
     image_avtar: require('../assets/images/avtarimg.png'),
     icon_search: require('../assets/images/search.png'),
     icon_cross: require('../assets/images/cross.png'),
     icon_done: require('../assets/images/Group592.png'),
      icon_done_selected: require('../assets/images/DoneJobs.png'),
     icon_camera: require('../assets/images/Group595.png'),
     icon_Group590: require('../assets/images/newOrder_Disabled.png'),
    icon_Group590_selected: require('../assets/images/enableAllJobs.png'),
     icon_dollar: require('../assets/images/dollar-note.png'),
     icon_credit: require('../assets/images/creditbill.png'),

    icon_eye: require('../assets/images/eye.png'),
    icon_inventory: require('../assets/images/inventory.png'),
    icon_placeholder: require('../assets/images/placeholder.png'),
    icon_bell: require('../assets/images/noun_Bell_1286844.png'),

    ico_orderList: require('../assets/images/orderList.png'),
    ico_phone: require('../assets/images/Group594.png'),
    ico_plusicon: require('../assets/images/plusicon.png'),
    icon_signout: require('../assets/images/icon_signout.png'),
    ico_order: require('../assets/images/Ongoing_disabled.png'),
    ico_order_selected: require('../assets/images/enableOnGoingJobs.png'),
    ico_fav_active: require('../assets/images/fav_mark.png'),
    ico_fav_disabled: require('../assets/images/fav.png'),
    ico_scan: require('../assets/images/scan.png'),
    ico_plus_bg: require('../assets/images/Group589.png'),
    icon_record: require('../assets/images/record.png'),
    icon_received: require('../assets/images/received.png'),
    icon_dashboard: require('../assets/images/dashboard.png'),
    icon_account_circle: require('../assets/images/profile_circle.png'),

    // icon_right: require('../assets/images/arrow_right.png'),
    // icon_search: require('../assets/images/search.png'),
     icon_fav_mark: require('../assets/images/fav_disabled.png'),
     icon_fav_mark_active: require('../assets/images/fav_active.png'),
    //
    // icon_setting: require('../assets/images/setting.png'),
    // icon_helpcenter: require('../assets/images/helpcenter.png'),
    // icon_aboutus: require('../assets/images/aboutus.png'),
    // icon_logout: require('../assets/images/icon_logout.png'),
    //
    // icon_white_back: require('../assets/images/icon_white_back.png'),
    // icon_back_arrow: require('../assets/images/icon_back_arrow.png'),
    // icon_arrow_right: require('../assets/images/icon_arrow_right.png'),
    // icon_right_cart: require('../assets/images/icon_right_cart.png'),
    //
    // icon_empty_cart: require('../assets/images/empty_cart.png'),
    // icon_valet: require('../assets/images/icon_valet.png'),
    // icon_bg: require('../assets/images/icon_bg.png'),
    // icon_tick: require('../assets/images/icon_tick.png'),
    // ico_line_dashed: require('../assets/images/ico_line_dashed.png'),
    // icon_camera: require('../assets/images/icon_camera.png'),
    // icon_location_red: require('../assets/images/icon_location_red.png'),
    // icon_location: require('../assets/images/icon_location.png'),
    //
    // icon_calender: require('../assets/images/calendar.png'),
    // icon_location_white: require('../assets/images/icon_location_white.png'),
    // float_button: require('../assets/images/float_button.png'),
    // icon_home_address: require('../assets/images/icon_home_address.png'),
    // icon_home_address_disabled: require('../assets/images/icon_home_address_disabled.png'),
    // icon_office_address_disabled: require('../assets/images/icon_office_address_disabled.png'),
    // icon_office_address: require('../assets/images/icon_office_address.png'),
    // md_map: require('../assets/images/md_map.png'),
    // icon_bg_rectangle: require('../assets/images/icon_bg_rectangle.png'),
    // icon_address_delete: require('../assets/images/icon_address_delete.png'),
    // icon_address_edit: require('../assets/images/icon_address_edit.png'),
    // ico_language_english_flag: require('../assets/images/ico_language_english_flag.png'),
    // ico_language_lao_flag: require('../assets/images/ico_language_lao_flag.png'),
    // icon_company_banner: require('../assets/images/icon_company_banner.png'),

};
